[build]
  publish = "public"  
  functions = "api"   

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"   

  # Timeout y tamaño máximo para funciones
  directory = "api"          
  included_files = ["api/*.js"]  

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/api/*"   
  [headers.values]
    Content-Type = "application/json"
