[build]
  publish = "public"
  functions = "api"

[[redirects]]
  # Redirige todas las solicitudes a /index.html para rutas que no sean API o webhook de Telegram
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  # No redireccionar la API
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  # No redireccionar el webhook de Telegram
  from = "/webhook/*"
  to = "/webhook/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/api/*"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/webhook/*"
  [headers.values]
    Content-Type = "application/json"
