[build]
  publish = "public"  
  functions = "api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

  # Timeout extendido para las funciones
  [functions.timeout]
  timeout = 26  
  external_node_modules = ["mongodb", "axios"]  

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/api/*"   
  [headers.values]
    Content-Type = "application/json"
