# Configuración de construcción
[build]
  publish = "public"  # Carpeta donde están los archivos estáticos
  functions = "api"   # Carpeta donde están las funciones serverless

# Redireccionamiento
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de funciones
[functions]
  node_bundler = "esbuild"  # Esbuild para empaquetar las funciones de Node.js
  external_node_modules = ["mongodb", "axios"]  # Módulos externos necesarios
  timeout = 26  # Timeout extendido para evitar que las funciones fallen en procesos largos

# Configuración de cabeceras (CORS y otros headers)
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"  # Permitir solicitudes desde cualquier origen (CORS)

[[headers]]
  for = "/api/*"  # Para todas las rutas que comienzan con /api/
  [headers.values]
    Content-Type = "application/json"  # Asegurarse de que el Content-Type sea JSON
